/* Generated from https://pod.solid-memo.com/shapes/<class>/v<N> by `npm run generate`. Do not edit: change the source and regenerate. */

import type { ShapeDescriptor } from "./shapeDescriptor.ts";
import type {
  AgentV1,
  AnswerV1,
  CardV1,
  CardV2,
  CardV3,
  CardV4,
  CardV5,
  CatalogV1,
  DeckV1,
  DeckV2,
  DeckV3,
  DeckV4,
  DeckV5,
  DeckV6,
  DeckScheduleV1,
  DistributionV1,
  DocumentReceiptV1,
  InstanceV1,
  InstanceV2,
  LibraryDeckV1,
  LibraryDeckV2,
  LibraryDeckV3,
  LibraryDeckV4,
  LibraryDeckV5,
  LibraryDeckSeriesV1,
  LibraryDeckSeriesV2,
  LibraryDeckSeriesV3,
  PreferencesV1,
  PreferencesV2,
  PreferencesV3,
  PreferencesV4,
  ReviewStateV1,
  ReviewStateV2,
} from "./types.generated.ts";

export const AGENT_V1: ShapeDescriptor<AgentV1> = {
  shape: "agent",
  version: 1,
  targetClass: "http://xmlns.com/foaf/0.1/Agent",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/agent/v1#shape",
  shapeDocument: "agent/v1",
  context: "any",
  fields: [
    { name: "name", predicate: "http://xmlns.com/foaf/0.1/name", kind: "string", cardinality: "one" },
    { name: "mbox", predicate: "http://xmlns.com/foaf/0.1/mbox", kind: "iri", cardinality: "optional" },
  ],
};

export const ANSWER_V1: ShapeDescriptor<AnswerV1> = {
  shape: "answer",
  version: 1,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Answer",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/answer/v1#shape",
  shapeDocument: "answer/v1",
  context: "any",
  fields: [
    { name: "deck", predicate: "https://pod.solid-memo.com/vocab/v1#answeredDeck", kind: "iri", cardinality: "one" },
    { name: "card", predicate: "https://pod.solid-memo.com/vocab/v1#answeredCard", kind: "iri", cardinality: "one" },
    { name: "direction", predicate: "https://pod.solid-memo.com/vocab/v1#answeredDirection", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#frontToBack","https://pod.solid-memo.com/vocab/v1#backToFront"] },
    { name: "grade", predicate: "https://pod.solid-memo.com/vocab/v1#grade", kind: "integer", cardinality: "one" },
    { name: "answeredAt", predicate: "https://pod.solid-memo.com/vocab/v1#answeredAt", kind: "dateTime", cardinality: "one" },
    { name: "studyDay", predicate: "https://pod.solid-memo.com/vocab/v1#answeredOn", kind: "string", cardinality: "one" },
    { name: "priorIntervalDays", predicate: "https://pod.solid-memo.com/vocab/v1#priorIntervalDays", kind: "integer", cardinality: "optional" },
    { name: "nextIntervalDays", predicate: "https://pod.solid-memo.com/vocab/v1#nextIntervalDays", kind: "integer", cardinality: "one" },
  ],
};

export const CARD_V1: ShapeDescriptor<CardV1> = {
  shape: "card",
  version: 1,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Card",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/card/v1#shape",
  shapeDocument: "card/v1",
  context: "any",
  fields: [
    { name: "front", predicate: "https://pod.solid-memo.com/vocab/v1#front", kind: "string", cardinality: "one" },
    { name: "back", predicate: "https://pod.solid-memo.com/vocab/v1#back", kind: "string", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
  ],
};

export const CARD_V2: ShapeDescriptor<CardV2> = {
  shape: "card",
  version: 2,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Card",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/card/v2#shape",
  shapeDocument: "card/v2",
  context: "any",
  fields: [
    { name: "front", predicate: "https://pod.solid-memo.com/vocab/v1#front", kind: "string", cardinality: "optional" },
    { name: "back", predicate: "https://pod.solid-memo.com/vocab/v1#back", kind: "string", cardinality: "optional" },
    { name: "frontImage", predicate: "https://pod.solid-memo.com/vocab/v1#frontImage", kind: "iri", cardinality: "optional" },
    { name: "backImage", predicate: "https://pod.solid-memo.com/vocab/v1#backImage", kind: "iri", cardinality: "optional" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
  ],
};

export const CARD_V3: ShapeDescriptor<CardV3> = {
  shape: "card",
  version: 3,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Card",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/card/v3#shape",
  shapeDocument: "card/v3",
  context: "any",
  fields: [
    { name: "front", predicate: "https://pod.solid-memo.com/vocab/v1#front", kind: "string", cardinality: "optional" },
    { name: "back", predicate: "https://pod.solid-memo.com/vocab/v1#back", kind: "string", cardinality: "optional" },
    { name: "frontImage", predicate: "https://pod.solid-memo.com/vocab/v1#frontImage", kind: "iri", cardinality: "optional" },
    { name: "backImage", predicate: "https://pod.solid-memo.com/vocab/v1#backImage", kind: "iri", cardinality: "optional" },
    { name: "frontNote", predicate: "https://pod.solid-memo.com/vocab/v1#frontNote", kind: "text", cardinality: "optional" },
    { name: "backLabel", predicate: "https://pod.solid-memo.com/vocab/v1#backLabel", kind: "text", cardinality: "optional" },
    { name: "backNote", predicate: "https://pod.solid-memo.com/vocab/v1#backNote", kind: "text", cardinality: "optional" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "deprecated", predicate: "http://www.w3.org/2002/07/owl#deprecated", kind: "boolean", cardinality: "optional" },
  ],
};

export const CARD_V4: ShapeDescriptor<CardV4> = {
  shape: "card",
  version: 4,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Card",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/card/v4#shape",
  shapeDocument: "card/v4",
  context: "any",
  fields: [
    { name: "front", predicate: "https://pod.solid-memo.com/vocab/v1#front", kind: "anyText", cardinality: "optional" },
    { name: "back", predicate: "https://pod.solid-memo.com/vocab/v1#back", kind: "anyText", cardinality: "optional" },
    { name: "frontImage", predicate: "https://pod.solid-memo.com/vocab/v1#frontImage", kind: "iri", cardinality: "optional" },
    { name: "backImage", predicate: "https://pod.solid-memo.com/vocab/v1#backImage", kind: "iri", cardinality: "optional" },
    { name: "frontImageDescription", predicate: "https://pod.solid-memo.com/vocab/v1#frontImageDescription", kind: "text", cardinality: "optional" },
    { name: "backImageDescription", predicate: "https://pod.solid-memo.com/vocab/v1#backImageDescription", kind: "text", cardinality: "optional" },
    { name: "frontNote", predicate: "https://pod.solid-memo.com/vocab/v1#frontNote", kind: "text", cardinality: "optional" },
    { name: "backLabel", predicate: "https://pod.solid-memo.com/vocab/v1#backLabel", kind: "text", cardinality: "optional" },
    { name: "backNote", predicate: "https://pod.solid-memo.com/vocab/v1#backNote", kind: "text", cardinality: "optional" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "deprecated", predicate: "http://www.w3.org/2002/07/owl#deprecated", kind: "boolean", cardinality: "optional" },
  ],
};

export const CARD_V5: ShapeDescriptor<CardV5> = {
  shape: "card",
  version: 5,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Card",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/card/v5#shape",
  shapeDocument: "card/v5",
  context: "any",
  fields: [
    { name: "front", predicate: "https://pod.solid-memo.com/vocab/v1#front", kind: "anyText", cardinality: "optional" },
    { name: "back", predicate: "https://pod.solid-memo.com/vocab/v1#back", kind: "anyText", cardinality: "optional" },
    { name: "frontImage", predicate: "https://pod.solid-memo.com/vocab/v1#frontImage", kind: "iri", cardinality: "optional" },
    { name: "backImage", predicate: "https://pod.solid-memo.com/vocab/v1#backImage", kind: "iri", cardinality: "optional" },
    { name: "frontImageDescription", predicate: "https://pod.solid-memo.com/vocab/v1#frontImageDescription", kind: "text", cardinality: "optional" },
    { name: "backImageDescription", predicate: "https://pod.solid-memo.com/vocab/v1#backImageDescription", kind: "text", cardinality: "optional" },
    { name: "frontNote", predicate: "https://pod.solid-memo.com/vocab/v1#frontNote", kind: "text", cardinality: "optional" },
    { name: "backLabel", predicate: "https://pod.solid-memo.com/vocab/v1#backLabel", kind: "text", cardinality: "optional" },
    { name: "backNote", predicate: "https://pod.solid-memo.com/vocab/v1#backNote", kind: "text", cardinality: "optional" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "deprecated", predicate: "http://www.w3.org/2002/07/owl#deprecated", kind: "boolean", cardinality: "optional" },
  ],
};

export const CATALOG_V1: ShapeDescriptor<CatalogV1> = {
  shape: "catalog",
  version: 1,
  targetClass: "http://www.w3.org/ns/dcat#Catalog",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/catalog/v1#shape",
  shapeDocument: "catalog/v1",
  context: "any",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "string", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "string", cardinality: "one" },
    { name: "publisher", predicate: "http://purl.org/dc/terms/publisher", kind: "iri", cardinality: "one" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
    { name: "themeTaxonomy", predicate: "http://www.w3.org/ns/dcat#themeTaxonomy", kind: "iri", cardinality: "many" },
    { name: "dataset", predicate: "http://www.w3.org/ns/dcat#dataset", kind: "iri", cardinality: "many" },
  ],
};

export const DECK_V1: ShapeDescriptor<DeckV1> = {
  shape: "deck",
  version: 1,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/deck/v1#inPod",
  shapeDocument: "deck/v1",
  context: "pod",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "string", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "string", cardinality: "many" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "string", cardinality: "optional" },
    { name: "cardsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#cardsDocument", kind: "iri", cardinality: "one" },
    { name: "reviewsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#reviewsDocument", kind: "iri", cardinality: "one" },
    { name: "source", predicate: "http://purl.org/dc/terms/source", kind: "iri", cardinality: "optional" },
  ],
};

export const DECK_V2: ShapeDescriptor<DeckV2> = {
  shape: "deck",
  version: 2,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/deck/v2#inPod",
  shapeDocument: "deck/v2",
  context: "pod",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "string", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "string", cardinality: "many" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "string", cardinality: "optional" },
    { name: "direction", predicate: "https://pod.solid-memo.com/vocab/v1#direction", kind: "enum", cardinality: "one", values: ["front-to-back","back-to-front","bidirectional"] },
    { name: "cardsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#cardsDocument", kind: "iri", cardinality: "one" },
    { name: "reviewsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#reviewsDocument", kind: "iri", cardinality: "one" },
    { name: "source", predicate: "http://purl.org/dc/terms/source", kind: "iri", cardinality: "optional" },
  ],
};

export const DECK_V3: ShapeDescriptor<DeckV3> = {
  shape: "deck",
  version: 3,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: ["http://www.w3.org/ns/dcat#Dataset"],
  absent: ["https://pod.solid-memo.com/vocab/v1#direction","http://purl.org/dc/terms/source"],
  shapeIri: "https://pod.solid-memo.com/shapes/deck/v3#inPod",
  shapeDocument: "deck/v3",
  context: "pod",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "string", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "string", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "iri", cardinality: "many" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "studyDirection", predicate: "https://pod.solid-memo.com/vocab/v1#studyDirection", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#frontToBack","https://pod.solid-memo.com/vocab/v1#backToFront","https://pod.solid-memo.com/vocab/v1#bidirectional"] },
    { name: "theme", predicate: "http://www.w3.org/ns/dcat#theme", kind: "iri", cardinality: "many" },
    { name: "keyword", predicate: "http://www.w3.org/ns/dcat#keyword", kind: "string", cardinality: "many" },
    { name: "distribution", predicate: "http://www.w3.org/ns/dcat#distribution", kind: "iri", cardinality: "many" },
    { name: "cardsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#cardsDocument", kind: "iri", cardinality: "one" },
    { name: "reviewsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#reviewsDocument", kind: "iri", cardinality: "one" },
    { name: "source", predicate: "http://www.w3.org/ns/prov#wasDerivedFrom", kind: "iri", cardinality: "optional" },
    { name: "newCardsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#deckNewCardsPerDay", kind: "integer", cardinality: "optional" },
    { name: "maxReviewsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#deckMaxReviewsPerDay", kind: "integer", cardinality: "optional" },
  ],
};

export const DECK_V4: ShapeDescriptor<DeckV4> = {
  shape: "deck",
  version: 4,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: ["http://www.w3.org/ns/dcat#Dataset"],
  absent: ["https://pod.solid-memo.com/vocab/v1#direction","http://purl.org/dc/terms/source"],
  shapeIri: "https://pod.solid-memo.com/shapes/deck/v4#inPod",
  shapeDocument: "deck/v4",
  context: "pod",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "text", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "text", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "iri", cardinality: "many" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "studyDirection", predicate: "https://pod.solid-memo.com/vocab/v1#studyDirection", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#frontToBack","https://pod.solid-memo.com/vocab/v1#backToFront","https://pod.solid-memo.com/vocab/v1#bidirectional"] },
    { name: "theme", predicate: "http://www.w3.org/ns/dcat#theme", kind: "iri", cardinality: "many" },
    { name: "keyword", predicate: "http://www.w3.org/ns/dcat#keyword", kind: "string", cardinality: "many" },
    { name: "distribution", predicate: "http://www.w3.org/ns/dcat#distribution", kind: "iri", cardinality: "many" },
    { name: "cardsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#cardsDocument", kind: "iri", cardinality: "one" },
    { name: "reviewsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#reviewsDocument", kind: "iri", cardinality: "one" },
    { name: "source", predicate: "http://www.w3.org/ns/prov#wasDerivedFrom", kind: "iri", cardinality: "optional" },
    { name: "newCardsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#deckNewCardsPerDay", kind: "integer", cardinality: "optional" },
    { name: "maxReviewsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#deckMaxReviewsPerDay", kind: "integer", cardinality: "optional" },
  ],
};

export const DECK_V5: ShapeDescriptor<DeckV5> = {
  shape: "deck",
  version: 5,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: ["http://www.w3.org/ns/dcat#Dataset"],
  absent: ["https://pod.solid-memo.com/vocab/v1#direction","http://purl.org/dc/terms/source"],
  shapeIri: "https://pod.solid-memo.com/shapes/deck/v5#inPod",
  shapeDocument: "deck/v5",
  context: "pod",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "text", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "text", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "iri", cardinality: "many" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "studyDirection", predicate: "https://pod.solid-memo.com/vocab/v1#studyDirection", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#frontToBack","https://pod.solid-memo.com/vocab/v1#backToFront","https://pod.solid-memo.com/vocab/v1#bidirectional"] },
    { name: "theme", predicate: "http://www.w3.org/ns/dcat#theme", kind: "iri", cardinality: "many" },
    { name: "keyword", predicate: "http://www.w3.org/ns/dcat#keyword", kind: "string", cardinality: "many" },
    { name: "distribution", predicate: "http://www.w3.org/ns/dcat#distribution", kind: "iri", cardinality: "many" },
    { name: "cardsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#cardsDocument", kind: "iri", cardinality: "one" },
    { name: "reviewsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#reviewsDocument", kind: "iri", cardinality: "one" },
    { name: "source", predicate: "http://www.w3.org/ns/prov#wasDerivedFrom", kind: "iri", cardinality: "optional" },
    { name: "newCardsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#deckNewCardsPerDay", kind: "integer", cardinality: "optional" },
    { name: "maxReviewsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#deckMaxReviewsPerDay", kind: "integer", cardinality: "optional" },
  ],
};

export const DECK_V6: ShapeDescriptor<DeckV6> = {
  shape: "deck",
  version: 6,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: ["http://www.w3.org/ns/dcat#Dataset"],
  absent: ["https://pod.solid-memo.com/vocab/v1#direction","http://purl.org/dc/terms/source"],
  shapeIri: "https://pod.solid-memo.com/shapes/deck/v6#inPod",
  shapeDocument: "deck/v6",
  context: "pod",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "text", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "text", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "iri", cardinality: "many" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "studyDirection", predicate: "https://pod.solid-memo.com/vocab/v1#studyDirection", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#frontToBack","https://pod.solid-memo.com/vocab/v1#backToFront","https://pod.solid-memo.com/vocab/v1#bidirectional"] },
    { name: "theme", predicate: "http://www.w3.org/ns/dcat#theme", kind: "iri", cardinality: "many" },
    { name: "keyword", predicate: "http://www.w3.org/ns/dcat#keyword", kind: "anyText", cardinality: "many" },
    { name: "distribution", predicate: "http://www.w3.org/ns/dcat#distribution", kind: "iri", cardinality: "many" },
    { name: "cardsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#cardsDocument", kind: "iri", cardinality: "one" },
    { name: "reviewsDocument", predicate: "https://pod.solid-memo.com/vocab/v1#reviewsDocument", kind: "iri", cardinality: "one" },
    { name: "source", predicate: "http://www.w3.org/ns/prov#wasDerivedFrom", kind: "iri", cardinality: "optional" },
    { name: "newCardsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#deckNewCardsPerDay", kind: "integer", cardinality: "optional" },
    { name: "maxReviewsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#deckMaxReviewsPerDay", kind: "integer", cardinality: "optional" },
  ],
};

export const DECK_SCHEDULE_V1: ShapeDescriptor<DeckScheduleV1> = {
  shape: "deckSchedule",
  version: 1,
  targetClass: "https://pod.solid-memo.com/vocab/v1#DeckSchedule",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/deck-schedule/v1#shape",
  shapeDocument: "deck-schedule/v1",
  context: "any",
  fields: [
    { name: "deck", predicate: "https://pod.solid-memo.com/vocab/v1#scheduleOf", kind: "iri", cardinality: "one" },
    { name: "cardsVersion", predicate: "https://pod.solid-memo.com/vocab/v1#cardsVersion", kind: "string", cardinality: "one" },
    { name: "reviewsVersion", predicate: "https://pod.solid-memo.com/vocab/v1#reviewsVersion", kind: "string", cardinality: "one" },
    { name: "direction", predicate: "https://pod.solid-memo.com/vocab/v1#scheduledDirection", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#frontToBack","https://pod.solid-memo.com/vocab/v1#backToFront","https://pod.solid-memo.com/vocab/v1#bidirectional"] },
    { name: "dayBoundaryHour", predicate: "https://pod.solid-memo.com/vocab/v1#scheduledDayBoundaryHour", kind: "integer", cardinality: "one" },
    { name: "studyDay", predicate: "https://pod.solid-memo.com/vocab/v1#scheduledOn", kind: "string", cardinality: "one" },
    { name: "dueOnDay", predicate: "https://pod.solid-memo.com/vocab/v1#dueOnDay", kind: "string", cardinality: "many" },
    { name: "unreviewed", predicate: "https://pod.solid-memo.com/vocab/v1#unreviewedCount", kind: "integer", cardinality: "one" },
    { name: "reviewedOnDay", predicate: "https://pod.solid-memo.com/vocab/v1#reviewedOnDayCount", kind: "integer", cardinality: "one" },
    { name: "introducedOnDay", predicate: "https://pod.solid-memo.com/vocab/v1#introducedOnDayCount", kind: "integer", cardinality: "one" },
  ],
};

export const DISTRIBUTION_V1: ShapeDescriptor<DistributionV1> = {
  shape: "distribution",
  version: 1,
  targetClass: "http://www.w3.org/ns/dcat#Distribution",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/distribution/v1#shape",
  shapeDocument: "distribution/v1",
  context: "any",
  fields: [
    { name: "accessUrl", predicate: "http://www.w3.org/ns/dcat#accessURL", kind: "iri", cardinality: "one" },
    { name: "downloadUrl", predicate: "http://www.w3.org/ns/dcat#downloadURL", kind: "iri", cardinality: "optional" },
    { name: "mediaType", predicate: "http://www.w3.org/ns/dcat#mediaType", kind: "iri", cardinality: "optional" },
    { name: "format", predicate: "http://purl.org/dc/terms/format", kind: "iri", cardinality: "optional" },
  ],
};

export const DOCUMENT_RECEIPT_V1: ShapeDescriptor<DocumentReceiptV1> = {
  shape: "documentReceipt",
  version: 1,
  targetClass: "https://pod.solid-memo.com/vocab/v1#DocumentReceipt",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/document-receipt/v1#shape",
  shapeDocument: "document-receipt/v1",
  context: "any",
  fields: [
    { name: "document", predicate: "https://pod.solid-memo.com/vocab/v1#receiptOf", kind: "iri", cardinality: "one" },
    { name: "version", predicate: "https://pod.solid-memo.com/vocab/v1#documentVersion", kind: "string", cardinality: "one" },
    { name: "conformedTo", predicate: "https://pod.solid-memo.com/vocab/v1#conformedTo", kind: "string", cardinality: "optional" },
    { name: "latestFormat", predicate: "https://pod.solid-memo.com/vocab/v1#latestFormat", kind: "boolean", cardinality: "optional" },
  ],
};

export const INSTANCE_V1: ShapeDescriptor<InstanceV1> = {
  shape: "instance",
  version: 1,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Instance",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/instance/v1#shape",
  shapeDocument: "instance/v1",
  context: "any",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "string", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "one" },
  ],
};

export const INSTANCE_V2: ShapeDescriptor<InstanceV2> = {
  shape: "instance",
  version: 2,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Instance",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/instance/v2#shape",
  shapeDocument: "instance/v2",
  context: "any",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "string", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "one" },
    { name: "replaces", predicate: "http://purl.org/dc/terms/replaces", kind: "iri", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
  ],
};

export const LIBRARY_DECK_V1: ShapeDescriptor<LibraryDeckV1> = {
  shape: "libraryDeck",
  version: 1,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: [],
  absent: ["https://pod.solid-memo.com/vocab/v1#cardsDocument","https://pod.solid-memo.com/vocab/v1#reviewsDocument"],
  shapeIri: "https://pod.solid-memo.com/shapes/deck/v1#inLibrary",
  shapeDocument: "deck/v1",
  context: "library",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "string", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "string", cardinality: "many" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "string", cardinality: "optional" },
    { name: "source", predicate: "http://purl.org/dc/terms/source", kind: "iri", cardinality: "many" },
  ],
};

export const LIBRARY_DECK_V2: ShapeDescriptor<LibraryDeckV2> = {
  shape: "libraryDeck",
  version: 2,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: [],
  absent: ["https://pod.solid-memo.com/vocab/v1#cardsDocument","https://pod.solid-memo.com/vocab/v1#reviewsDocument"],
  shapeIri: "https://pod.solid-memo.com/shapes/deck/v2#inLibrary",
  shapeDocument: "deck/v2",
  context: "library",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "string", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "string", cardinality: "many" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "string", cardinality: "optional" },
    { name: "direction", predicate: "https://pod.solid-memo.com/vocab/v1#direction", kind: "enum", cardinality: "one", values: ["front-to-back","back-to-front","bidirectional"] },
    { name: "source", predicate: "http://purl.org/dc/terms/source", kind: "iri", cardinality: "many" },
  ],
};

export const LIBRARY_DECK_V3: ShapeDescriptor<LibraryDeckV3> = {
  shape: "libraryDeck",
  version: 3,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: ["http://www.w3.org/ns/dcat#Dataset"],
  absent: ["https://pod.solid-memo.com/vocab/v1#direction","https://pod.solid-memo.com/vocab/v1#cardsDocument","https://pod.solid-memo.com/vocab/v1#reviewsDocument","http://purl.org/dc/terms/source","https://pod.solid-memo.com/vocab/v1#deckNewCardsPerDay","https://pod.solid-memo.com/vocab/v1#deckMaxReviewsPerDay"],
  shapeIri: "https://pod.solid-memo.com/shapes/deck/v3#inLibrary",
  shapeDocument: "deck/v3",
  context: "library",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "string", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "string", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
    { name: "issued", predicate: "http://purl.org/dc/terms/issued", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "iri", cardinality: "many" },
    { name: "publisher", predicate: "http://purl.org/dc/terms/publisher", kind: "iri", cardinality: "one" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "studyDirection", predicate: "https://pod.solid-memo.com/vocab/v1#studyDirection", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#frontToBack","https://pod.solid-memo.com/vocab/v1#backToFront","https://pod.solid-memo.com/vocab/v1#bidirectional"] },
    { name: "theme", predicate: "http://www.w3.org/ns/dcat#theme", kind: "iri", cardinality: "many" },
    { name: "keyword", predicate: "http://www.w3.org/ns/dcat#keyword", kind: "string", cardinality: "many" },
    { name: "language", predicate: "http://purl.org/dc/terms/language", kind: "iri", cardinality: "many" },
    { name: "version", predicate: "http://www.w3.org/ns/dcat#version", kind: "string", cardinality: "one" },
    { name: "versionNotes", predicate: "http://www.w3.org/ns/adms#versionNotes", kind: "string", cardinality: "optional" },
    { name: "inSeries", predicate: "http://www.w3.org/ns/dcat#inSeries", kind: "iri", cardinality: "one" },
    { name: "isVersionOf", predicate: "http://www.w3.org/ns/dcat#isVersionOf", kind: "iri", cardinality: "one" },
    { name: "prev", predicate: "http://www.w3.org/ns/dcat#prev", kind: "iri", cardinality: "optional" },
    { name: "previousVersion", predicate: "http://www.w3.org/ns/dcat#previousVersion", kind: "iri", cardinality: "optional" },
    { name: "distribution", predicate: "http://www.w3.org/ns/dcat#distribution", kind: "iri", cardinality: "many" },
    { name: "wasDerivedFrom", predicate: "http://www.w3.org/ns/prov#wasDerivedFrom", kind: "iri", cardinality: "many" },
  ],
};

export const LIBRARY_DECK_V4: ShapeDescriptor<LibraryDeckV4> = {
  shape: "libraryDeck",
  version: 4,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: ["http://www.w3.org/ns/dcat#Dataset"],
  absent: ["https://pod.solid-memo.com/vocab/v1#direction","https://pod.solid-memo.com/vocab/v1#cardsDocument","https://pod.solid-memo.com/vocab/v1#reviewsDocument","http://purl.org/dc/terms/source","https://pod.solid-memo.com/vocab/v1#deckNewCardsPerDay","https://pod.solid-memo.com/vocab/v1#deckMaxReviewsPerDay"],
  shapeIri: "https://pod.solid-memo.com/shapes/deck/v4#inLibrary",
  shapeDocument: "deck/v4",
  context: "library",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "text", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "text", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
    { name: "issued", predicate: "http://purl.org/dc/terms/issued", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "iri", cardinality: "many" },
    { name: "publisher", predicate: "http://purl.org/dc/terms/publisher", kind: "iri", cardinality: "one" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "studyDirection", predicate: "https://pod.solid-memo.com/vocab/v1#studyDirection", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#frontToBack","https://pod.solid-memo.com/vocab/v1#backToFront","https://pod.solid-memo.com/vocab/v1#bidirectional"] },
    { name: "theme", predicate: "http://www.w3.org/ns/dcat#theme", kind: "iri", cardinality: "many" },
    { name: "keyword", predicate: "http://www.w3.org/ns/dcat#keyword", kind: "string", cardinality: "many" },
    { name: "language", predicate: "http://purl.org/dc/terms/language", kind: "iri", cardinality: "many" },
    { name: "version", predicate: "http://www.w3.org/ns/dcat#version", kind: "string", cardinality: "one" },
    { name: "versionNotes", predicate: "http://www.w3.org/ns/adms#versionNotes", kind: "string", cardinality: "optional" },
    { name: "inSeries", predicate: "http://www.w3.org/ns/dcat#inSeries", kind: "iri", cardinality: "one" },
    { name: "isVersionOf", predicate: "http://www.w3.org/ns/dcat#isVersionOf", kind: "iri", cardinality: "one" },
    { name: "prev", predicate: "http://www.w3.org/ns/dcat#prev", kind: "iri", cardinality: "optional" },
    { name: "previousVersion", predicate: "http://www.w3.org/ns/dcat#previousVersion", kind: "iri", cardinality: "optional" },
    { name: "distribution", predicate: "http://www.w3.org/ns/dcat#distribution", kind: "iri", cardinality: "many" },
    { name: "wasDerivedFrom", predicate: "http://www.w3.org/ns/prov#wasDerivedFrom", kind: "iri", cardinality: "many" },
  ],
};

export const LIBRARY_DECK_V5: ShapeDescriptor<LibraryDeckV5> = {
  shape: "libraryDeck",
  version: 5,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Deck",
  additionalTypes: ["http://www.w3.org/ns/dcat#Dataset"],
  absent: ["https://pod.solid-memo.com/vocab/v1#direction","https://pod.solid-memo.com/vocab/v1#cardsDocument","https://pod.solid-memo.com/vocab/v1#reviewsDocument","http://purl.org/dc/terms/source","https://pod.solid-memo.com/vocab/v1#deckNewCardsPerDay","https://pod.solid-memo.com/vocab/v1#deckMaxReviewsPerDay"],
  shapeIri: "https://pod.solid-memo.com/shapes/library-deck/v5#inLibrary",
  shapeDocument: "library-deck/v5",
  context: "library",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "text", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "text", cardinality: "one" },
    { name: "created", predicate: "http://purl.org/dc/terms/created", kind: "dateTime", cardinality: "optional" },
    { name: "modified", predicate: "http://purl.org/dc/terms/modified", kind: "dateTime", cardinality: "optional" },
    { name: "issued", predicate: "http://purl.org/dc/terms/issued", kind: "dateTime", cardinality: "optional" },
    { name: "creator", predicate: "http://purl.org/dc/terms/creator", kind: "iri", cardinality: "many" },
    { name: "publisher", predicate: "http://purl.org/dc/terms/publisher", kind: "iri", cardinality: "one" },
    { name: "license", predicate: "http://purl.org/dc/terms/license", kind: "iri", cardinality: "optional" },
    { name: "studyDirection", predicate: "https://pod.solid-memo.com/vocab/v1#studyDirection", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#frontToBack","https://pod.solid-memo.com/vocab/v1#backToFront","https://pod.solid-memo.com/vocab/v1#bidirectional"] },
    { name: "theme", predicate: "http://www.w3.org/ns/dcat#theme", kind: "iri", cardinality: "many" },
    { name: "keyword", predicate: "http://www.w3.org/ns/dcat#keyword", kind: "text", cardinality: "many" },
    { name: "language", predicate: "http://purl.org/dc/terms/language", kind: "iri", cardinality: "many" },
    { name: "version", predicate: "http://www.w3.org/ns/dcat#version", kind: "string", cardinality: "one" },
    { name: "versionNotes", predicate: "http://www.w3.org/ns/adms#versionNotes", kind: "string", cardinality: "optional" },
    { name: "inSeries", predicate: "http://www.w3.org/ns/dcat#inSeries", kind: "iri", cardinality: "one" },
    { name: "isVersionOf", predicate: "http://www.w3.org/ns/dcat#isVersionOf", kind: "iri", cardinality: "one" },
    { name: "prev", predicate: "http://www.w3.org/ns/dcat#prev", kind: "iri", cardinality: "optional" },
    { name: "previousVersion", predicate: "http://www.w3.org/ns/dcat#previousVersion", kind: "iri", cardinality: "optional" },
    { name: "distribution", predicate: "http://www.w3.org/ns/dcat#distribution", kind: "iri", cardinality: "many" },
    { name: "wasDerivedFrom", predicate: "http://www.w3.org/ns/prov#wasDerivedFrom", kind: "iri", cardinality: "many" },
  ],
};

export const LIBRARY_DECK_SERIES_V1: ShapeDescriptor<LibraryDeckSeriesV1> = {
  shape: "libraryDeckSeries",
  version: 1,
  targetClass: "http://www.w3.org/ns/dcat#DatasetSeries",
  additionalTypes: ["http://www.w3.org/ns/dcat#Dataset"],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/deck-series/v1#inLibrary",
  shapeDocument: "deck-series/v1",
  context: "library",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "string", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "string", cardinality: "one" },
    { name: "publisher", predicate: "http://purl.org/dc/terms/publisher", kind: "iri", cardinality: "one" },
    { name: "theme", predicate: "http://www.w3.org/ns/dcat#theme", kind: "iri", cardinality: "many" },
    { name: "keyword", predicate: "http://www.w3.org/ns/dcat#keyword", kind: "string", cardinality: "many" },
    { name: "first", predicate: "http://www.w3.org/ns/dcat#first", kind: "iri", cardinality: "one" },
    { name: "last", predicate: "http://www.w3.org/ns/dcat#last", kind: "iri", cardinality: "one" },
    { name: "hasVersion", predicate: "http://www.w3.org/ns/dcat#hasVersion", kind: "iri", cardinality: "many" },
    { name: "hasCurrentVersion", predicate: "http://www.w3.org/ns/dcat#hasCurrentVersion", kind: "iri", cardinality: "one" },
  ],
};

export const LIBRARY_DECK_SERIES_V2: ShapeDescriptor<LibraryDeckSeriesV2> = {
  shape: "libraryDeckSeries",
  version: 2,
  targetClass: "http://www.w3.org/ns/dcat#DatasetSeries",
  additionalTypes: ["http://www.w3.org/ns/dcat#Dataset"],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/deck-series/v2#inLibrary",
  shapeDocument: "deck-series/v2",
  context: "library",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "text", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "text", cardinality: "one" },
    { name: "publisher", predicate: "http://purl.org/dc/terms/publisher", kind: "iri", cardinality: "one" },
    { name: "theme", predicate: "http://www.w3.org/ns/dcat#theme", kind: "iri", cardinality: "many" },
    { name: "keyword", predicate: "http://www.w3.org/ns/dcat#keyword", kind: "string", cardinality: "many" },
    { name: "first", predicate: "http://www.w3.org/ns/dcat#first", kind: "iri", cardinality: "one" },
    { name: "last", predicate: "http://www.w3.org/ns/dcat#last", kind: "iri", cardinality: "one" },
    { name: "hasVersion", predicate: "http://www.w3.org/ns/dcat#hasVersion", kind: "iri", cardinality: "many" },
    { name: "hasCurrentVersion", predicate: "http://www.w3.org/ns/dcat#hasCurrentVersion", kind: "iri", cardinality: "one" },
  ],
};

export const LIBRARY_DECK_SERIES_V3: ShapeDescriptor<LibraryDeckSeriesV3> = {
  shape: "libraryDeckSeries",
  version: 3,
  targetClass: "http://www.w3.org/ns/dcat#DatasetSeries",
  additionalTypes: ["http://www.w3.org/ns/dcat#Dataset"],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/deck-series/v3#inLibrary",
  shapeDocument: "deck-series/v3",
  context: "library",
  fields: [
    { name: "title", predicate: "http://purl.org/dc/terms/title", kind: "text", cardinality: "one" },
    { name: "description", predicate: "http://purl.org/dc/terms/description", kind: "text", cardinality: "one" },
    { name: "publisher", predicate: "http://purl.org/dc/terms/publisher", kind: "iri", cardinality: "one" },
    { name: "theme", predicate: "http://www.w3.org/ns/dcat#theme", kind: "iri", cardinality: "many" },
    { name: "keyword", predicate: "http://www.w3.org/ns/dcat#keyword", kind: "anyText", cardinality: "many" },
    { name: "first", predicate: "http://www.w3.org/ns/dcat#first", kind: "iri", cardinality: "one" },
    { name: "last", predicate: "http://www.w3.org/ns/dcat#last", kind: "iri", cardinality: "one" },
    { name: "hasVersion", predicate: "http://www.w3.org/ns/dcat#hasVersion", kind: "iri", cardinality: "many" },
    { name: "hasCurrentVersion", predicate: "http://www.w3.org/ns/dcat#hasCurrentVersion", kind: "iri", cardinality: "one" },
  ],
};

export const PREFERENCES_V1: ShapeDescriptor<PreferencesV1> = {
  shape: "preferences",
  version: 1,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Preferences",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/preferences/v1#shape",
  shapeDocument: "preferences/v1",
  context: "any",
  fields: [
    { name: "newCardsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#newCardsPerDay", kind: "integer", cardinality: "optional" },
    { name: "maxReviewsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#maxReviewsPerDay", kind: "integer", cardinality: "optional" },
    { name: "dayBoundaryHour", predicate: "https://pod.solid-memo.com/vocab/v1#dayBoundaryHour", kind: "integer", cardinality: "optional" },
    { name: "answerScale", predicate: "https://pod.solid-memo.com/vocab/v1#answerScale", kind: "enum", cardinality: "optional", values: ["sm2","minimal"] },
    { name: "developerMode", predicate: "https://pod.solid-memo.com/vocab/v1#developerMode", kind: "boolean", cardinality: "optional" },
  ],
};

export const PREFERENCES_V2: ShapeDescriptor<PreferencesV2> = {
  shape: "preferences",
  version: 2,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Preferences",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/preferences/v2#shape",
  shapeDocument: "preferences/v2",
  context: "any",
  fields: [
    { name: "newCardsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#newCardsPerDay", kind: "integer", cardinality: "one" },
    { name: "maxReviewsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#maxReviewsPerDay", kind: "integer", cardinality: "one" },
    { name: "dayBoundaryHour", predicate: "https://pod.solid-memo.com/vocab/v1#dayBoundaryHour", kind: "integer", cardinality: "one" },
    { name: "answerScale", predicate: "https://pod.solid-memo.com/vocab/v1#answerScale", kind: "enum", cardinality: "one", values: ["sm2","minimal"] },
    { name: "developerMode", predicate: "https://pod.solid-memo.com/vocab/v1#developerMode", kind: "boolean", cardinality: "one" },
  ],
};

export const PREFERENCES_V3: ShapeDescriptor<PreferencesV3> = {
  shape: "preferences",
  version: 3,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Preferences",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/preferences/v3#shape",
  shapeDocument: "preferences/v3",
  context: "any",
  fields: [
    { name: "newCardsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#newCardsPerDay", kind: "integer", cardinality: "one" },
    { name: "maxReviewsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#maxReviewsPerDay", kind: "integer", cardinality: "one" },
    { name: "dayBoundaryHour", predicate: "https://pod.solid-memo.com/vocab/v1#dayBoundaryHour", kind: "integer", cardinality: "one" },
    { name: "answerScale", predicate: "https://pod.solid-memo.com/vocab/v1#answerScale", kind: "enum", cardinality: "one", values: ["sm2","minimal"] },
    { name: "developerMode", predicate: "https://pod.solid-memo.com/vocab/v1#developerMode", kind: "boolean", cardinality: "one" },
    { name: "invalidDataPolicy", predicate: "https://pod.solid-memo.com/vocab/v1#invalidDataPolicy", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#blockInstance","https://pod.solid-memo.com/vocab/v1#blockSubject","https://pod.solid-memo.com/vocab/v1#warnOnly"] },
  ],
};

export const PREFERENCES_V4: ShapeDescriptor<PreferencesV4> = {
  shape: "preferences",
  version: 4,
  targetClass: "https://pod.solid-memo.com/vocab/v1#Preferences",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/preferences/v4#shape",
  shapeDocument: "preferences/v4",
  context: "any",
  fields: [
    { name: "newCardsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#newCardsPerDay", kind: "integer", cardinality: "one" },
    { name: "maxReviewsPerDay", predicate: "https://pod.solid-memo.com/vocab/v1#maxReviewsPerDay", kind: "integer", cardinality: "one" },
    { name: "dayBoundaryHour", predicate: "https://pod.solid-memo.com/vocab/v1#dayBoundaryHour", kind: "integer", cardinality: "one" },
    { name: "answerScale", predicate: "https://pod.solid-memo.com/vocab/v1#answerScale", kind: "enum", cardinality: "one", values: ["sm2","minimal"] },
    { name: "developerMode", predicate: "https://pod.solid-memo.com/vocab/v1#developerMode", kind: "boolean", cardinality: "one" },
    { name: "invalidDataPolicy", predicate: "https://pod.solid-memo.com/vocab/v1#invalidDataPolicy", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#blockInstance","https://pod.solid-memo.com/vocab/v1#blockSubject","https://pod.solid-memo.com/vocab/v1#warnOnly"] },
    { name: "theme", predicate: "https://pod.solid-memo.com/vocab/v1#theme", kind: "iriEnum", cardinality: "one", values: ["https://pod.solid-memo.com/vocab/v1#systemTheme","https://pod.solid-memo.com/vocab/v1#lightTheme","https://pod.solid-memo.com/vocab/v1#darkTheme"] },
  ],
};

export const REVIEW_STATE_V1: ShapeDescriptor<ReviewStateV1> = {
  shape: "reviewState",
  version: 1,
  targetClass: "https://pod.solid-memo.com/vocab/v1#ReviewState",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/review-state/v1#shape",
  shapeDocument: "review-state/v1",
  context: "any",
  fields: [
    { name: "easeFactor", predicate: "https://pod.solid-memo.com/vocab/v1#easeFactor", kind: "decimal", cardinality: "one" },
    { name: "intervalDays", predicate: "https://pod.solid-memo.com/vocab/v1#intervalDays", kind: "integer", cardinality: "one" },
    { name: "repetitions", predicate: "https://pod.solid-memo.com/vocab/v1#repetitions", kind: "integer", cardinality: "one" },
    { name: "due", predicate: "https://pod.solid-memo.com/vocab/v1#due", kind: "string", cardinality: "one" },
    { name: "firstReviewedAt", predicate: "https://pod.solid-memo.com/vocab/v1#firstReviewedAt", kind: "dateTime", cardinality: "one" },
    { name: "lastReviewedAt", predicate: "https://pod.solid-memo.com/vocab/v1#lastReviewedAt", kind: "dateTime", cardinality: "one" },
    { name: "previousEaseFactor", predicate: "https://pod.solid-memo.com/vocab/v1#previousEaseFactor", kind: "decimal", cardinality: "optional" },
    { name: "previousIntervalDays", predicate: "https://pod.solid-memo.com/vocab/v1#previousIntervalDays", kind: "integer", cardinality: "optional" },
    { name: "previousRepetitions", predicate: "https://pod.solid-memo.com/vocab/v1#previousRepetitions", kind: "integer", cardinality: "optional" },
    { name: "previousDue", predicate: "https://pod.solid-memo.com/vocab/v1#previousDue", kind: "string", cardinality: "optional" },
    { name: "previousLastReviewedAt", predicate: "https://pod.solid-memo.com/vocab/v1#previousLastReviewedAt", kind: "dateTime", cardinality: "optional" },
  ],
};

export const REVIEW_STATE_V2: ShapeDescriptor<ReviewStateV2> = {
  shape: "reviewState",
  version: 2,
  targetClass: "https://pod.solid-memo.com/vocab/v1#ReviewState",
  additionalTypes: [],
  absent: [],
  shapeIri: "https://pod.solid-memo.com/shapes/review-state/v2#shape",
  shapeDocument: "review-state/v2",
  context: "any",
  fields: [
    { name: "easeFactor", predicate: "https://pod.solid-memo.com/vocab/v1#easeFactor", kind: "decimal", cardinality: "one" },
    { name: "intervalDays", predicate: "https://pod.solid-memo.com/vocab/v1#intervalDays", kind: "integer", cardinality: "one" },
    { name: "repetitions", predicate: "https://pod.solid-memo.com/vocab/v1#repetitions", kind: "integer", cardinality: "one" },
    { name: "due", predicate: "https://pod.solid-memo.com/vocab/v1#due", kind: "string", cardinality: "one" },
    { name: "firstReviewedAt", predicate: "https://pod.solid-memo.com/vocab/v1#firstReviewedAt", kind: "dateTime", cardinality: "one" },
    { name: "lastReviewedAt", predicate: "https://pod.solid-memo.com/vocab/v1#lastReviewedAt", kind: "dateTime", cardinality: "one" },
    { name: "previousEaseFactor", predicate: "https://pod.solid-memo.com/vocab/v1#previousEaseFactor", kind: "decimal", cardinality: "optional" },
    { name: "previousIntervalDays", predicate: "https://pod.solid-memo.com/vocab/v1#previousIntervalDays", kind: "integer", cardinality: "optional" },
    { name: "previousRepetitions", predicate: "https://pod.solid-memo.com/vocab/v1#previousRepetitions", kind: "integer", cardinality: "optional" },
    { name: "previousDue", predicate: "https://pod.solid-memo.com/vocab/v1#previousDue", kind: "string", cardinality: "optional" },
    { name: "previousLastReviewedAt", predicate: "https://pod.solid-memo.com/vocab/v1#previousLastReviewedAt", kind: "dateTime", cardinality: "optional" },
  ],
};

/** Every descriptor by kind and version. */
export const SHAPES = {
  agent: { 1: AGENT_V1 },
  answer: { 1: ANSWER_V1 },
  card: { 1: CARD_V1, 2: CARD_V2, 3: CARD_V3, 4: CARD_V4, 5: CARD_V5 },
  catalog: { 1: CATALOG_V1 },
  deck: { 1: DECK_V1, 2: DECK_V2, 3: DECK_V3, 4: DECK_V4, 5: DECK_V5, 6: DECK_V6 },
  deckSchedule: { 1: DECK_SCHEDULE_V1 },
  distribution: { 1: DISTRIBUTION_V1 },
  documentReceipt: { 1: DOCUMENT_RECEIPT_V1 },
  instance: { 1: INSTANCE_V1, 2: INSTANCE_V2 },
  libraryDeck: { 1: LIBRARY_DECK_V1, 2: LIBRARY_DECK_V2, 3: LIBRARY_DECK_V3, 4: LIBRARY_DECK_V4, 5: LIBRARY_DECK_V5 },
  libraryDeckSeries: { 1: LIBRARY_DECK_SERIES_V1, 2: LIBRARY_DECK_SERIES_V2, 3: LIBRARY_DECK_SERIES_V3 },
  preferences: { 1: PREFERENCES_V1, 2: PREFERENCES_V2, 3: PREFERENCES_V3, 4: PREFERENCES_V4 },
  reviewState: { 1: REVIEW_STATE_V1, 2: REVIEW_STATE_V2 },
} as const;

/** Every descriptor, for selection by class, version and context. */
export const ALL_SHAPES: readonly ShapeDescriptor[] = [
  AGENT_V1,
  ANSWER_V1,
  CARD_V1,
  CARD_V2,
  CARD_V3,
  CARD_V4,
  CARD_V5,
  CATALOG_V1,
  DECK_V1,
  DECK_V2,
  DECK_V3,
  DECK_V4,
  DECK_V5,
  DECK_V6,
  DECK_SCHEDULE_V1,
  DISTRIBUTION_V1,
  DOCUMENT_RECEIPT_V1,
  INSTANCE_V1,
  INSTANCE_V2,
  LIBRARY_DECK_V1,
  LIBRARY_DECK_V2,
  LIBRARY_DECK_V3,
  LIBRARY_DECK_V4,
  LIBRARY_DECK_V5,
  LIBRARY_DECK_SERIES_V1,
  LIBRARY_DECK_SERIES_V2,
  LIBRARY_DECK_SERIES_V3,
  PREFERENCES_V1,
  PREFERENCES_V2,
  PREFERENCES_V3,
  PREFERENCES_V4,
  REVIEW_STATE_V1,
  REVIEW_STATE_V2,
];
