import { fragmentIdOf } from "../subjectUrl.ts";

/**
 * One release of a deck as plain data (docs/deck-library.md, A
 * version): its own metadata, every card, chapter, step and distractor
 * it has, retired ones included, and how it was made. The release
 * rules (release/*Rules.ts) read this view, never Turtle, so the
 * library's command (packages/shacl/node/deckLibrary.ts, which builds
 * it from the release's quads) and the Studio check a release alike.
 * Every list keeps the order the release states it in, which the
 * problems follow.
 */

export const DCAT_NS = "http://www.w3.org/ns/dcat#";
export const DCTERMS_NS = "http://purl.org/dc/terms/";
export const SCHEMA_NS = "https://schema.org/";

/** A value a release states: an IRI, a blank node, or a literal with its language ("" for none) and datatype. */
export type ReleaseTerm =
  | { kind: "iri"; value: string }
  | { kind: "blank"; value: string }
  | ReleaseText;

/** A literal: text, a number or a date, as the release writes it. */
export interface ReleaseText {
  kind: "literal";
  value: string;
  /** The language tag, "" when untagged. */
  language: string;
  datatype: string;
}

/** What every subject of the outline has: its IRI and whether it is retired (owl:deprecated true). */
export interface ReleaseSubject {
  iri: string;
  retired: boolean;
}

/** A card (solid-memo:Card). Its texts are the literals it states, in order. */
export interface ReleaseCard extends ReleaseSubject {
  front: ReleaseText[];
  back: ReleaseText[];
  backLabel: ReleaseText[];
  frontNote: ReleaseText[];
  backNote: ReleaseText[];
  /** What it names by solid-memo:distractor, whatever each is. */
  distractors: ReleaseTerm[];
}

/** A course chapter (solid-memo:Chapter). Links keep only the IRIs. */
export interface ReleaseChapter extends ReleaseSubject {
  title: ReleaseText[];
  description: ReleaseText[];
  isPartOf: string[];
  /** The values of schema:position, as written. */
  positions: string[];
  reviewQuestions: string[];
}

/** A course step (solid-memo:Step). */
export interface ReleaseStep extends ReleaseSubject {
  theory: ReleaseText[];
  isPartOf: string[];
  positions: string[];
  checkedBy: string[];
}

/**
 * A distractor: a subject typed solid-memo:Distractor (`typed`), or one
 * a card names as its distractor without being one, which the course
 * rules name and whose text is still held to its card's format.
 */
export interface ReleaseDistractor extends ReleaseSubject {
  typed: boolean;
  text: ReleaseText[];
  note: ReleaseText[];
}

/** A prov:Activity of the release; `generating` when the release states it was generated by it. */
export interface ReleaseActivity {
  iri: string;
  generating: boolean;
}

/** One statement of a subject's predicate, for what may be stated on any subject. */
export interface ReleaseStatement {
  subject: string;
  object: ReleaseTerm;
}

export interface ReleaseModel {
  /** The release's own address: the document, which is the deck. */
  url: string;
  /** Every subject typed solid-memo:Deck, each once. */
  decks: string[];
  /** The IRIs the release itself is typed (dcat:Dataset, schema:Course, …). */
  types: string[];
  version: ReleaseTerm[];
  title: ReleaseText[];
  description: ReleaseText[];
  keywords: ReleaseTerm[];
  themes: ReleaseTerm[];
  languages: ReleaseTerm[];
  issued: ReleaseText[];
  modified: ReleaseText[];
  versionNotes: ReleaseText[];
  studyDirection: ReleaseTerm[];
  inSeries: ReleaseTerm[];
  isVersionOf: ReleaseTerm[];
  publisher: ReleaseTerm[];
  prev: ReleaseTerm[];
  previousVersion: ReleaseTerm[];
  distribution: ReleaseTerm[];
  /** The licence (dcterms:license). */
  licence: ReleaseTerm[];
  /** What it was compiled from (prov:wasDerivedFrom). */
  sources: ReleaseTerm[];
  activities: ReleaseActivity[];
  cards: ReleaseCard[];
  chapters: ReleaseChapter[];
  steps: ReleaseStep[];
  /** The typed distractors first, then those only named. */
  distractors: ReleaseDistractor[];
  /** Every solid-memo:distractor statement, of any subject. */
  distractorLinks: ReleaseStatement[];
  /** Every solid-memo:textFormat statement, of any subject. */
  textFormats: ReleaseStatement[];
}

/** The kinds of subject a release publishes for good: a later version retires one, never removes it. */
export type ReleaseKind = "card" | "chapter" | "step" | "distractor";

/** The subjects of a kind: cards, chapters, steps, or typed distractors. */
export function subjectsOf(model: ReleaseModel, kind: ReleaseKind): ReleaseSubject[] {
  switch (kind) {
    case "card":
      return model.cards;
    case "chapter":
      return model.chapters;
    case "step":
      return model.steps;
    case "distractor":
      return model.distractors.filter((d) => d.typed);
  }
}

/** The fragment ids of the subjects of a kind (`#sweden` → "sweden"): what a release publishes for good. */
export function publishedIds(model: ReleaseModel, kind: ReleaseKind): string[] {
  return subjectsOf(model, kind).map((subject) => fragmentIdOf(subject.iri));
}

/** The version a release states, when it states one, a whole number from 1. */
export function versionOf(model: ReleaseModel): number | undefined {
  const [stated, ...more] = model.version;
  return more.length === 0 && stated?.kind === "literal" && /^[1-9][0-9]*$/.test(stated.value) ? Number(stated.value) : undefined;
}

/** The languages of texts, "" for untagged, each once, in order. */
export function languagesOf(texts: readonly ReleaseText[]): string[] {
  return [...new Set(texts.map((text) => text.language))];
}

/** A model with nothing in it but its address: what a test or a blank draft starts from. */
export function emptyReleaseModel(url: string): ReleaseModel {
  return {
    url,
    decks: [],
    types: [],
    version: [],
    title: [],
    description: [],
    keywords: [],
    themes: [],
    languages: [],
    issued: [],
    modified: [],
    versionNotes: [],
    studyDirection: [],
    inSeries: [],
    isVersionOf: [],
    publisher: [],
    prev: [],
    previousVersion: [],
    distribution: [],
    licence: [],
    sources: [],
    activities: [],
    cards: [],
    chapters: [],
    steps: [],
    distractors: [],
    distractorLinks: [],
    textFormats: [],
  };
}
