import type { CardV5 } from "@solid-memo/vocab/types.generated";
import { SM } from "@solid-memo/vocab/vocab.generated";
import { blankDraft, NOTHING_PUBLISHED, type DraftTriple, type PublishedIds, type ReleaseDraft } from "../release/releaseDraft.ts";

/**
 * Drafts as plain data, for the tests of the draft's changes: a course
 * at DRAFT with two chapters, the first with two steps, and its
 * questions, every subject a fragment of DRAFT.
 */
export const DRAFT = "https://pod.example/solid-memo/main/drafts/solid/v2/release.ttl";
export const of = (id: string) => `${DRAFT}#${id}`;
export const NOW = "2026-10-10T10:00:00.000Z";

const PROV = "http://www.w3.org/ns/prov#";
const RDF_TYPE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

export function card(front: string, extra: Partial<CardV5> = {}): CardV5 {
  return { front: { en: front }, back: { en: `${front}!` }, distractor: [], ...extra };
}

/** A statement of the draft naming an IRI. */
export function link(subject: string, predicate: string, object: string): DraftTriple {
  return { subject, predicate, object: { kind: "iri", value: object } };
}

/**
 * The course: chapter `ch-a` (steps `ch-a-1` asking `q-a-1a` and
 * `ch-a-2` asking `q-a-2a`, and review question `q-a-r01`) and chapter
 * `ch-b` (no step yet); `q-a-1a` has distractors `q-a-1a-d1` and
 * `q-a-1a-d2`; `q-loose` is asked nowhere. It was generated by
 * `#compilation`, which used `<https://source.example/>`.
 */
export function courseDraft(published: PublishedIds = NOTHING_PUBLISHED): ReleaseDraft {
  const blank = blankDraft({ url: DRAFT, course: true, title: { en: "Solid" }, now: NOW });
  const triples: DraftTriple[] = [
    link(DRAFT, `${PROV}wasGeneratedBy`, of("compilation")),
    link(of("compilation"), RDF_TYPE, `${PROV}Activity`),
    link(of("compilation"), `${PROV}used`, "https://source.example/"),
    { subject: "https://source.example/", predicate: "http://purl.org/dc/terms/title", object: { kind: "literal", value: "Source", language: "", datatype: "http://www.w3.org/2001/XMLSchema#string" } },
  ];
  return {
    ...blank,
    root: { ...blank.root, wasDerivedFrom: ["https://source.example/"] },
    chapters: [
      { id: "ch-a", data: { title: { en: "A" }, course: DRAFT, position: 0, reviewQuestion: [of("q-a-r01")] } },
      { id: "ch-b", data: { title: { en: "B" }, course: DRAFT, position: 1, reviewQuestion: [] } },
    ],
    steps: [
      { id: "ch-a-1", data: { theory: { en: "One" }, chapter: of("ch-a"), position: 0, checkedBy: [of("q-a-1a")] } },
      { id: "ch-a-2", data: { theory: { en: "Two" }, chapter: of("ch-a"), position: 1, checkedBy: [of("q-a-2a")] } },
    ],
    cards: [
      { id: "q-a-1a", data: card("1a", { distractor: [of("q-a-1a-d1"), of("q-a-1a-d2")], created: NOW }) },
      { id: "q-a-2a", data: card("2a") },
      { id: "q-a-r01", data: card("r01") },
      { id: "q-loose", data: card("loose") },
    ],
    distractors: [
      { id: "q-a-1a-d1", data: { text: { en: "No 1" } } },
      { id: "q-a-1a-d2", data: { text: { en: "No 2" }, note: { en: "Why" } } },
    ],
    triples,
    published,
  };
}

/** A plain deck at DRAFT, with one card. */
export function deckDraft(): ReleaseDraft {
  const blank = blankDraft({ url: DRAFT, course: false, title: { en: "Words" }, now: NOW });
  return { ...blank, root: { ...blank.root, studyDirection: SM.bidirectional as ReleaseDraft["root"]["studyDirection"] }, cards: [{ id: "w1", data: card("w1") }] };
}

/**
 * A course that can be played (domain/release/trial.ts): the course
 * without chapter `ch-b`, each question it asks with two distractors.
 */
export function playableCourseDraft(): ReleaseDraft {
  const draft = courseDraft();
  const options = (cardId: string) => [of(`${cardId}-d1`), of(`${cardId}-d2`)];
  const asked = ["q-a-2a", "q-a-r01"];
  return {
    ...draft,
    chapters: draft.chapters.filter((chapter) => chapter.id !== "ch-b"),
    cards: draft.cards.map((node) => (asked.includes(node.id) ? { ...node, data: { ...node.data, distractor: options(node.id) } } : node)),
    distractors: [
      ...draft.distractors,
      ...asked.flatMap((cardId) => [1, 2].map((n) => ({ id: `${cardId}-d${n}`, data: { text: { en: `${cardId} no ${n}` } } }))),
    ],
  };
}
